source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'figaro', '~> 1.1.1'
gem 'devise', '~> 3.4.1'
gem 'pundit', '~> 1.0.0'
gem 'bcrypt', '~> 3.1.10'
gem 'passenger', '~> 5.0.7'
gem 'foundation-rails', '~> 5.5.2.1'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'web-console', '~> 2.0'
  gem 'guard', '~> 2.12.5'
  gem 'guard-minitest', '~> 2.4.4'
  gem 'minitest-rails-capybara', '~> 2.1.1'
  gem 'minitest-reporters', '~> 1.0.16'
  gem 'poltergeist', '~> 1.6.0'
  gem 'pry', '~> 0.10.1'
  gem 'pry-rails', '~> 0.3.4'
  gem 'pry-rescue', '~> 1.4.2'
  gem 'launchy', '~> 2.4.3'
end
